skip-check:
  - CKV_K8S_11
  - CKV_K8S_43
  - CKV_K8S_12
  - CKV_K8S_13
  - CKV_K8S_15
  - CKV_K8S_14
  - CKV_K8S_21
  - CKV_SECRET_6
  - CKV_K8S_10
  - CKV_DOCKER_2
  # "Minimize the admission of pods which lack an associated NetworkPolicy"
  - CKV2_K8S_6
