apiVersion: skaffold/v3
kind: Config
metadata:
  name: magnifhir
build:
  artifacts:
    - image: magnifhir
      context: .
      docker:
        dockerfile: Dockerfile
    - image: load-sample-data
      context: hack/
      docker:
        dockerfile: hack/k8s/load-sample-data.Dockerfile
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
      - hack/k8s
  helm:
    releases:
      - name: hapi-fhir-server
        remoteChart: hapi-fhir-jpaserver
        version: 0.11.0
        setValues:
          postgresql.auth.postgresPassword: secretpassword
        repo: https://hapifhir.github.io/hapi-fhir-jpaserver-starter/
deploy:
  helm: {}
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: magnifhir
    namespace: default
    port: 8080
    localPort: 8080
