apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - load-fhir-data-job.yaml

configMapGenerator:
  - name: magnifhir-appsettings
    files:
      - appsettings.Production.json
