apiVersion: batch/v1
kind: Job
metadata:
  name: load-sample-data
spec:
  template:
    spec:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: Never
      automountServiceAccountToken: false
      initContainers:
        - name: wait-for-fhir-server
          image: docker.io/curlimages/curl:7.84.0@sha256:5a2a25d96aa941ea2fc47acc50122f7c3d007399a075df61a82d6d2c3a567a2b
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: FHIR_SERVER_URL
              value: "http://hapi-fhir-server-hapi-fhir-jpaserver:8080/fhir"
          command: ["/bin/sh", "-c"]
          args:
            - |
              until [ "$(curl -s -o /dev/null -L -w '%{http_code}' "$FHIR_SERVER_URL/metadata")" == "200" ]; do
                echo "$(date): Waiting for FHIR server @ $FHIR_SERVER_URL to be up";
                sleep 15;
              done;
      containers:
        - name: load-sample-data
          image: load-sample-data
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: FHIR_SERVER_URL
              value: "http://hapi-fhir-server-hapi-fhir-jpaserver:8080/fhir"
